--
-- PostgreSQL database dump
--

-- Dumped from database version 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: jobs; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (1, 11, 1, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 100712, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (2, 68, 9, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 162147, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (3, 9, 8, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 246764, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (4, 66, 4, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 241739, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (5, 116, 5, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 25360, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (6, 77, 5, 'Aenean lectus. Pellentesque eget nunc.', 129843, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (7, 121, 8, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 137443, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (8, 120, 7, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 187741, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (9, 25, 11, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 253347, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (10, 23, 3, 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 36100, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (11, 2, 2, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 65816, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (12, 59, 10, 'Pellentesque at nulla. Suspendisse potenti.', 89362, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (13, 4, 4, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 33229, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (14, 17, 4, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 52111, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (15, 36, 5, 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 185647, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (16, 114, 4, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 221560, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (17, 103, 10, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 190740, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (18, 120, 3, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 213239, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (19, 61, 5, 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 66086, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (20, 89, 12, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 104174, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (21, 55, 1, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 73227, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (22, 60, 6, 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 124776, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (23, 43, 3, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 118186, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (24, 15, 6, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 246298, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (25, 48, 3, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 245390, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (26, 120, 13, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 40090, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (27, 62, 1, 'Phasellus sit amet erat. Nulla tempus.', 95113, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (28, 81, 11, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 185460, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (29, 61, 4, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 38062, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (30, 89, 5, 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', 31226, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (31, 32, 6, 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 173776, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (32, 93, 13, 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 53091, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (33, 108, 11, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 230539, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (34, 93, 10, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 229468, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (35, 119, 6, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 201682, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (36, 99, 5, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 64786, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (37, 64, 4, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 137374, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (38, 67, 11, 'In hac habitasse platea dictumst.', 26324, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (39, 97, 13, 'Aliquam erat volutpat.', 177161, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (40, 117, 11, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 143962, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (41, 107, 9, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 29747, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (42, 36, 11, 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 133504, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (43, 43, 12, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 80848, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (44, 24, 3, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 265869, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (45, 19, 9, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 37541, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (46, 111, 6, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 214167, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (47, 66, 13, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 108330, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (48, 104, 4, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 213225, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (49, 78, 3, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 78214, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (50, 74, 10, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', 137951, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (51, 69, 4, 'Phasellus in felis. Donec semper sapien a libero.', 74448, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (52, 84, 5, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 171386, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (53, 59, 8, 'Vestibulum ac est lacinia nisi venenatis tristique.', 74463, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (54, 121, 13, 'Integer a nibh.', 183445, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (55, 62, 9, 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 123415, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (56, 6, 12, 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 105404, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (57, 71, 3, 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 45159, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (58, 85, 10, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 92944, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (59, 24, 4, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 88095, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (60, 35, 2, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 183405, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (61, 65, 9, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 99305, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (62, 43, 5, 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 49012, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (63, 108, 7, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 257172, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (64, 75, 13, 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 219857, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (65, 14, 13, 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 261307, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (66, 115, 7, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 160448, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (67, 7, 7, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 36191, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (68, 9, 7, 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 133989, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (69, 81, 3, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 68651, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (70, 8, 3, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 71539, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (71, 118, 9, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 154046, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (72, 37, 4, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 93583, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (73, 116, 13, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 178635, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (74, 78, 11, 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 267886, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (75, 118, 7, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 130481, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (76, 59, 10, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 201025, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (77, 26, 2, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 100402, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (78, 3, 11, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 41967, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (79, 70, 11, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 252163, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (80, 100, 7, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 171839, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (81, 57, 3, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 165869, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (82, 55, 2, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 37570, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (83, 31, 6, 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 125020, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (84, 65, 11, 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 128563, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (85, 72, 4, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 130826, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (86, 25, 3, 'Proin interdum mauris non ligula pellentesque ultrices.', 134317, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (87, 121, 4, 'Fusce posuere felis sed lacus.', 256310, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (88, 81, 3, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 142188, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (89, 43, 10, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 201209, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (90, 120, 10, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 79536, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (91, 40, 10, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 120446, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (92, 16, 11, 'Vivamus in felis eu sapien cursus vestibulum.', 89442, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (93, 46, 6, 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 163724, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (94, 91, 1, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.', 107981, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (95, 55, 13, 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 27570, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (96, 8, 12, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 86981, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (97, 76, 9, 'Mauris ullamcorper purus sit amet nulla.', 215640, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (98, 22, 9, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 174565, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (99, 4, 9, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 30864, false);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (100, 13, 3, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 110307, true);
INSERT INTO public.jobs (id, "companyId", "roleId", description, salary, active) VALUES (101, 10, 2, 'Lorem ipsum dolor sit amet.', 90000, true);


--
-- Name: jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jobs_id_seq', 101, true);


--
-- PostgreSQL database dump complete
--

